Repository nimblehq/infrastructure-templates, pull requests merged in 2023-08, with the labels that each got.

#198 [#192] Update variables to use static values or locales when appropriate
  skeleton/aws/modules/alb/main.tf
  skeleton/aws/modules/alb/variables.tf
  skeleton/aws/modules/ecs/main.tf
  skeleton/aws/modules/ecs/variables.tf
  skeleton/aws/modules/rds/main.tf
  skeleton/aws/modules/rds/variables.tf
  skeleton/aws/modules/vpc/main.tf
  skeleton/aws/modules/vpc/variables.tf
  src/templates/aws/addons/alb.ts
  src/templates/aws/addons/cloudwatch.test.ts
  src/templates/aws/addons/cloudwatch.ts
Labels: type : chore

#210 [#207] Fix: The tfsec fails due to aws-iam-no-policy-wildcards rule
  templates/addons/aws/modules/iam_groups/main.tf
Labels: type : bug

#206 [#191] Add prompt to enable Terraform Cloud
  .github/wiki/Getting-Started.md
  package-lock.json
  src/commands/generate/index.test.ts
  src/commands/generate/index.ts
  src/commands/install/index.test.ts
  src/generators/addons/terraformCloud/index.test.ts
  src/generators/addons/terraformCloud/index.ts
  src/generators/addons/versionControl/index.test.ts
  src/generators/addons/versionControl/index.ts
  templates/terraform/core/main.tf
  templates/terraform/shared/main.tf
  test/matchers/file.ts
  test/matchers/index.d.ts
Labels: type : feature
