Repository nimblehq/infrastructure-templates, pull requests merged in 2023-11, with the labels that each got.

#242 [#235] Update prompts to show all options
  src/commands/install/index.ts
  src/generators/addons/versionControl/index.test.ts
  src/generators/addons/versionControl/index.ts
Labels: type : chore

#251 [#250] Fix: Command generate not found
  .eslintrc
  bin/run
  package-lock.json
  package.json
  src/generators/terraform/types.ts
  src/helpers/file.test.ts
  src/helpers/file.ts
Labels: type : bug, priority : high

#258 [Chore] Bump version to 2.2.0
  package.json
Labels: type : chore

#259 Release - 2.2.0
  .eslintrc
  .github/release-drafter.yml
  .github/workflows/draft-new-release.yml
  bin/run
  package-lock.json
  package.json
  src/commands/install/index.ts
  src/generators/addons/versionControl/index.test.ts
  src/generators/addons/versionControl/index.ts
  src/generators/terraform/types.ts
  src/helpers/file.test.ts
  src/helpers/file.ts
Labels: type : release

#261 [#246] Fix: Wrong syntax for the policy document of full_iam_access_policy
  package-lock.json
  templates/addons/aws/modules/iam_groups/data.tf
  templates/addons/aws/modules/iam_groups/main.tf
Labels: type : bug

#237 [#234] Add version increment workflow
  .github/workflows/increment-version.yml
Labels: type : feature, priority : high
