Repository nimblehq/infrastructure-templates, pull requests merged in 2023-09, with the labels that each got.

#216 [#215] Fix: The template can not be published
  .gitignore
  package-lock.json
  package.json
  tsconfig.json
Labels: type : bug

#218 Release - 2.0.1
  .gitignore
  package-lock.json
  package.json
  tsconfig.json
Labels: type : release

#221 [#219] Fix: Cannot use 'import.meta' outside a module
  .github/wiki/Getting-Started.md
  bin/run
  package-lock.json
  package.json
  src/generators/addons/terraformCloud/index.ts
  src/helpers/terraform.test.ts
  src/helpers/terraform.ts
Labels: type : bug

#223 Release - 2.0.2
  .github/wiki/Getting-Started.md
  bin/run
  package-lock.json
  package.json
  src/generators/addons/terraformCloud/index.ts
  src/helpers/terraform.test.ts
  src/helpers/terraform.ts
Labels: type : release

#228 [Chore] Add IDE files to .gitignore
  .gitignore
  templates/terraform/gitignore
Labels: type : chore

#222 [#220] Fix: namespace and environment are misused
  src/generators/addons/aws/modules/alb.ts
  src/generators/addons/aws/modules/bastion.ts
  src/generators/addons/aws/modules/cloudwatch.ts
  src/generators/addons/aws/modules/core/securityGroup.ts
  src/generators/addons/aws/modules/core/vpc.ts
  src/generators/addons/aws/modules/ecr.ts
  src/generators/addons/aws/modules/ecs.ts
  src/generators/addons/aws/modules/rds.ts
  src/generators/addons/aws/modules/s3.ts
  src/generators/addons/aws/modules/ssm.ts
  src/generators/terraform/index.ts
  templates/addons/aws/README.md
  templates/addons/aws/modules/alb/main.tf
  templates/addons/aws/modules/alb/variables.tf
  templates/addons/aws/modules/bastion/main.tf
  templates/addons/aws/modules/bastion/variables.tf
  templates/addons/aws/modules/cloudwatch/main.tf
  templates/addons/aws/modules/cloudwatch/variables.tf
  templates/addons/aws/modules/ecr/main.tf
  templates/addons/aws/modules/ecr/variables.tf
  templates/addons/aws/modules/ecs/main.tf
  templates/addons/aws/modules/ecs/service.json.tftpl
  templates/addons/aws/modules/ecs/variables.tf
  templates/addons/aws/modules/rds/main.tf
  templates/addons/aws/modules/rds/variables.tf
  templates/addons/aws/modules/s3/main.tf
  templates/addons/aws/modules/s3/variables.tf
  templates/addons/aws/modules/security_group/variables.tf
  templates/addons/aws/modules/ssm/main.tf
  templates/addons/aws/modules/ssm/variables.tf
  templates/addons/aws/modules/vpc/main.tf
  templates/addons/aws/modules/vpc/variables.tf
  templates/terraform/core/variables.tf
  templates/terraform/shared/variables.tf
Labels: type : bug

#229 Release - 2.1.0
  .gitignore
  src/generators/addons/aws/modules/alb.ts
  src/generators/addons/aws/modules/bastion.ts
  src/generators/addons/aws/modules/cloudwatch.ts
  src/generators/addons/aws/modules/core/securityGroup.ts
  src/generators/addons/aws/modules/core/vpc.ts
  src/generators/addons/aws/modules/ecr.ts
  src/generators/addons/aws/modules/ecs.ts
  src/generators/addons/aws/modules/rds.ts
  src/generators/addons/aws/modules/s3.ts
  src/generators/addons/aws/modules/ssm.ts
  src/generators/terraform/index.ts
  templates/addons/aws/README.md
  templates/addons/aws/modules/alb/main.tf
  templates/addons/aws/modules/alb/variables.tf
  templates/addons/aws/modules/bastion/main.tf
  templates/addons/aws/modules/bastion/variables.tf
  templates/addons/aws/modules/cloudwatch/main.tf
  templates/addons/aws/modules/cloudwatch/variables.tf
  templates/addons/aws/modules/ecr/main.tf
  templates/addons/aws/modules/ecr/variables.tf
  templates/addons/aws/modules/ecs/main.tf
  templates/addons/aws/modules/ecs/service.json.tftpl
  templates/addons/aws/modules/ecs/variables.tf
  templates/addons/aws/modules/rds/main.tf
  templates/addons/aws/modules/rds/variables.tf
  templates/addons/aws/modules/s3/main.tf
  templates/addons/aws/modules/s3/variables.tf
  templates/addons/aws/modules/security_group/variables.tf
  templates/addons/aws/modules/ssm/main.tf
  templates/addons/aws/modules/ssm/variables.tf
  templates/addons/aws/modules/vpc/main.tf
  templates/addons/aws/modules/vpc/variables.tf
  templates/terraform/core/variables.tf
  templates/terraform/gitignore
  templates/terraform/shared/variables.tf
Labels: type : release
